USE [VehicleParkingManagementDB];
GO

SET XACT_ABORT ON;

BEGIN TRY
    BEGIN TRANSACTION;

    ALTER TABLE dbo.PARKING_USER ADD
        CONSTRAINT FK_PARKING_USER_CreatedBy FOREIGN KEY (CreatedBy) REFERENCES dbo.PARKING_USER (UserID),
        CONSTRAINT FK_PARKING_USER_UpdatedBy FOREIGN KEY (UpdatedBy) REFERENCES dbo.PARKING_USER (UserID);

    ALTER TABLE dbo.PARKING_VEHICLE_TYPE ADD
        CONSTRAINT FK_PARKING_VEHICLE_TYPE_CreatedBy FOREIGN KEY (CreatedBy) REFERENCES dbo.PARKING_USER (UserID),
        CONSTRAINT FK_PARKING_VEHICLE_TYPE_UpdatedBy FOREIGN KEY (UpdatedBy) REFERENCES dbo.PARKING_USER (UserID);

    ALTER TABLE dbo.PARKING_SPACE ADD
        CONSTRAINT FK_PARKING_SPACE_CreatedBy FOREIGN KEY (CreatedBy) REFERENCES dbo.PARKING_USER (UserID),
        CONSTRAINT FK_PARKING_SPACE_UpdatedBy FOREIGN KEY (UpdatedBy) REFERENCES dbo.PARKING_USER (UserID);

    ALTER TABLE dbo.PARKING_RATE ADD
        CONSTRAINT FK_PARKING_RATE_CreatedBy FOREIGN KEY (CreatedBy) REFERENCES dbo.PARKING_USER (UserID),
        CONSTRAINT FK_PARKING_RATE_UpdatedBy FOREIGN KEY (UpdatedBy) REFERENCES dbo.PARKING_USER (UserID);

    ALTER TABLE dbo.PARKING_CUSTOMER ADD
        CONSTRAINT FK_PARKING_CUSTOMER_CreatedBy FOREIGN KEY (CreatedBy) REFERENCES dbo.PARKING_USER (UserID),
        CONSTRAINT FK_PARKING_CUSTOMER_UpdatedBy FOREIGN KEY (UpdatedBy) REFERENCES dbo.PARKING_USER (UserID);

    ALTER TABLE dbo.PARKING_CUSTOMER_VEHICLE ADD
        CONSTRAINT FK_PARKING_CUSTOMER_VEHICLE_CreatedBy FOREIGN KEY (CreatedBy) REFERENCES dbo.PARKING_USER (UserID),
        CONSTRAINT FK_PARKING_CUSTOMER_VEHICLE_UpdatedBy FOREIGN KEY (UpdatedBy) REFERENCES dbo.PARKING_USER (UserID);

    ALTER TABLE dbo.PARKING_MONTHLY_CONTRACT ADD
        CONSTRAINT FK_PARKING_MONTHLY_CONTRACT_CreatedBy FOREIGN KEY (CreatedBy) REFERENCES dbo.PARKING_USER (UserID),
        CONSTRAINT FK_PARKING_MONTHLY_CONTRACT_UpdatedBy FOREIGN KEY (UpdatedBy) REFERENCES dbo.PARKING_USER (UserID);

    ALTER TABLE dbo.PARKING_TICKET ADD
        CONSTRAINT FK_PARKING_TICKET_CreatedBy FOREIGN KEY (CreatedBy) REFERENCES dbo.PARKING_USER (UserID),
        CONSTRAINT FK_PARKING_TICKET_UpdatedBy FOREIGN KEY (UpdatedBy) REFERENCES dbo.PARKING_USER (UserID);

    ALTER TABLE dbo.PARKING_PAYMENT ADD
        CONSTRAINT FK_PARKING_PAYMENT_CreatedBy FOREIGN KEY (CreatedBy) REFERENCES dbo.PARKING_USER (UserID),
        CONSTRAINT FK_PARKING_PAYMENT_UpdatedBy FOREIGN KEY (UpdatedBy) REFERENCES dbo.PARKING_USER (UserID);

    ALTER TABLE dbo.PARKING_MONTHLY_PAYMENT ADD
        CONSTRAINT FK_PARKING_MONTHLY_PAYMENT_CreatedBy FOREIGN KEY (CreatedBy) REFERENCES dbo.PARKING_USER (UserID),
        CONSTRAINT FK_PARKING_MONTHLY_PAYMENT_UpdatedBy FOREIGN KEY (UpdatedBy) REFERENCES dbo.PARKING_USER (UserID);

 

    CREATE INDEX IX_PARKING_SPACE_TypeStatus
        ON dbo.PARKING_SPACE (VehicleTypeID, SpaceStatus, ActiveStatus);

    CREATE INDEX IX_PARKING_RATE_CurrentRate
        ON dbo.PARKING_RATE (VehicleTypeID, ActiveStatus, EffectiveFrom, EffectiveTo);

    CREATE INDEX IX_PARKING_CUSTOMER_Search
        ON dbo.PARKING_CUSTOMER (MobileNumber, CustomerName);

    CREATE INDEX IX_PARKING_CUSTOMER_VEHICLE_Customer
        ON dbo.PARKING_CUSTOMER_VEHICLE (CustomerID, ActiveStatus);

    CREATE INDEX IX_PARKING_CUSTOMER_VEHICLE_Type
        ON dbo.PARKING_CUSTOMER_VEHICLE (VehicleTypeID, ActiveStatus);

    CREATE INDEX IX_PARKING_MONTHLY_CONTRACT_Search
        ON dbo.PARKING_MONTHLY_CONTRACT (VehicleID, ContractStatus, StartDate, EndDate);

    /* Only one ACTIVE monthly contract can exist for a vehicle. */
    CREATE UNIQUE INDEX UX_PARKING_MONTHLY_CONTRACT_ActiveVehicle
        ON dbo.PARKING_MONTHLY_CONTRACT (VehicleID)
        WHERE ContractStatus = 'ACTIVE';

    CREATE INDEX IX_PARKING_TICKET_CurrentParking
        ON dbo.PARKING_TICKET (TicketStatus, EntryDateTime);

    /* A vehicle and a space may each appear in only one open visit.
       ExitDateTime must be populated when a visit is completed/cancelled. */
    CREATE UNIQUE INDEX UX_PARKING_TICKET_OpenVehicle
        ON dbo.PARKING_TICKET (VehicleID)
        WHERE ExitDateTime IS NULL;

    CREATE UNIQUE INDEX UX_PARKING_TICKET_OpenSpace
        ON dbo.PARKING_TICKET (SpaceID)
        WHERE ExitDateTime IS NULL;

    CREATE INDEX IX_PARKING_PAYMENT_Date
        ON dbo.PARKING_PAYMENT (PaymentDateTime, PaymentStatus);

    CREATE INDEX IX_PARKING_MONTHLY_PAYMENT_Date
        ON dbo.PARKING_MONTHLY_PAYMENT (PaymentDateTime, PaymentStatus);

	CREATE UNIQUE INDEX UX_PARKING_RATE_Active_Type_Unit
		ON dbo.PARKING_RATE (VehicleTypeID, RateUnit)
		WHERE ActiveStatus = 1;

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF XACT_STATE() <> 0
        ROLLBACK TRANSACTION;
    THROW;
END CATCH;
GO